### ISSUE TITLE
Create the ability to pass parameter via the command line

### ISSUE THREAD

**Issue by beauremus** [fermi-controls/datalogger-to-ml#1]
Check out [argparse](https://docs.python.org/3/library/argparse.html) for documentation.

**Variables to parameterize**
- [x] DEVICE_LIMIT - optional, default 0 for all devices
- [x] DEVICE_FILE - optional, default stdin - filename variable not yet created
- [x] OUTPUT_FILE - optional, default stdout - filename variable not yet created
- [x] START_TIME - required, datetime variable not yet created
- [x] END_TIME - required, datetime variable not yet created
- [x] DURATION - required, datetime variable not yet created
- [x] NODE - optional, default None - string variable not yet created

The option will be `START_TIME` *AND* `END_TIME` or `DURATION`.

**Comment by sakshi-fermi** [comment]
DEVICE_FILE -> Unsure about what's needed as default. Currently the default is just DeviceList.csv

**Comment by beauremus** [comment]
The default should be standard input so that someone can use the command line to pass output from another coming line program to this one.

**Comment by beauremus** [comment]
It shouldn't have a default value.
