### ISSUE TITLE
Create Nanny Script

### ISSUE THREAD

**Issue by beauremus** [fermi-controls/datalogger-to-ml#12]
The Nanny script is responsible for calling the DAQ script with certain parameters per the L-CAPE project.
This script allows concerns to be separated. Instead of dpmData.py being a do all script, it will be generic and the Nanny script can pass arguments to the DAQ script to make it specifically useful for L-CAPE. The idea is that dpmData.py could be useful for other projects in the future.
When that day comes we should move it out into its own project.
The Nanny script should be responsible for generating the device requests list and naming the output files. It can be responsible for coordinating runs of the DAQ script also, although the current plan is to use a CronJob.

**Comment by beauremus** [comment]
I forgot to mention that the agreed output naming convention loosely follows the [IS0 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) standard and is of the form `20210101T130000PT10M-1_0_0.h5` where `20210101` is the YYYYMMDD date separated from time with a `T` where `130000` represents,1 PM and `P` indicates a period of duration in this case `T10M` for 10 minutes. The hyphen separates the time, date, and duration from the device request list version `1_0_0` that uses the [semantic versioning standard](https://semver.org/) to represent `v1.0.0`.

**Comment by sakshi-fermi** [comment]
### To do

- [ ] Move the "readURL" method from [https://github.com/fermi-controls/datalogger-to-ml/blob/main/helperMethods.py](url) to the Nanny script.

**Comment by beauremus** [comment]
Closed by e3b800b9940b6dd53bce8a3f692a23948cc6b8d8.
