### ISSUE TITLE
Stopping point for old data collector

### ISSUE THREAD

**Issue by sakshi-fermi** [fermi-controls/datalogger-to-ml#21]
The old data collector script should know when to stop collecting data. 
Further discussion needed for handling scenarios where intermittent errors occur which may stop the script from collecting older data.

**Comment by sakshi-fermi** [comment]
> Further discussion needed for handling scenarios where intermittent errors occur which may stop the script from collecting older data.
The current logic (used in both [nanny.py](https://github.com/fermi-controls/datalogger-to-ml/blob/main/nanny.py) and [old_data_collector.py](https://github.com/fermi-controls/datalogger-to-ml/blob/main/old_data_collector.py)) handles those  and does not stop data collection.

**Comment by sakshi-fermi** [comment]
> The old data collector script should know when to stop collecting data.
With the latest commit, data collection can go until January 1, 2005.

**Comment by beauremus** [comment]
When an empty `.h5` file is produced, there is no more data. This is a fine stopping place but may be too aggressive.

Is there a way to know when one device has no data?

**Comment by beauremus** [comment]
We, developers, can't answer this question. We need input from ML analysts. We will output meta-information about DAQ in #6 as a way to help make this determination.
